version: '3'

services:
  cassandra-host-1:
    hostname: cassa1
    image: cassandra:latest
    container_name: cassandra-host-1
    networks:
      cassandra-local:
    environment:
      - CASSANDRA_SEEDS=cassandra-host-1,cassandra-host-2,cassandra-host-3
      - CASSANDRA_ENDPOINT_SNITCH=RackInferringSnitch
      - CASSANDRA_LISTEN_ADDRESS=cassandra-host-1
    ports:
      - "9042:9042"

  cassandra-host-2:
    hostname: cassa2
    image: cassandra:latest
    container_name: cassandra-host-2
    networks:
      cassandra-local:
    environment:
      - CASSANDRA_SEEDS=cassandra-host-1,cassandra-host-2,cassandra-host-3
      - CASSANDRA_ENDPOINT_SNITCH=RackInferringSnitch
      - CASSANDRA_LISTEN_ADDRESS=cassandra-host-2
    ports:
      - "9043:9042"

  cassandra-host-3:
    hostname: cassa3
    image: cassandra:latest
    container_name: cassandra-host-3
    networks:
      cassandra-local:
    environment:
      - CASSANDRA_SEEDS=cassandra-host-1,cassandra-host-2,cassandra-host-3
      - CASSANDRA_ENDPOINT_SNITCH=RackInferringSnitch
      - CASSANDRA_LISTEN_ADDRESS=cassandra-host-3
    ports:
      - "9044:9042"

networks:
  cassandra-local:
    driver: bridge