version: '3'

services:
  cassandra-host-1:
    hostname: cassa1
    image: cassandra:latest
    container_name: cassandra-host-1
    networks:
      cassandra-local:
        ipv4_address: 192.168.1.200
    environment:
      - CASSANDRA_SEEDS=cassandra-host-1,cassandra-host-2,cassandra-host-3
      - CASSANDRA_ENDPOINT_SNITCH=RackInferringSnitch
      - CASSANDRA_LISTEN_ADDRESS=192.168.1.200
    ports:
      - "9042:9042"
    healthcheck:
        test: ["CMD", "cqlsh", "-e", "describe keyspaces" ]
        interval: 5s
        timeout: 5s
        retries: 60

  cassandra-host-2:
    hostname: cassa2
    image: cassandra:latest
    container_name: cassandra-host-2
    networks:
      cassandra-local:
        ipv4_address: 192.168.1.201
    environment:
      - CASSANDRA_SEEDS=cassandra-host-1,cassandra-host-2,cassandra-host-3
      - CASSANDRA_ENDPOINT_SNITCH=RackInferringSnitch
      - CASSANDRA_LISTEN_ADDRESS=192.168.1.201
    ports:
      - "9042:9042"
    healthcheck:
        test: ["CMD", "cqlsh", "-e", "describe keyspaces" ]
        interval: 5s
        timeout: 5s
        retries: 60
    depends_on:
      cassandra-host-1:
        condition: service_healthy

  cassandra-host-3:
    hostname: cassa3
    image: cassandra:latest
    container_name: cassandra-host-3
    networks:
      cassandra-local:
        ipv4_address: 192.168.1.202
    environment:
      - CASSANDRA_SEEDS=cassandra-host-1,cassandra-host-2,cassandra-host-3
      - CASSANDRA_ENDPOINT_SNITCH=RackInferringSnitch
      - CASSANDRA_LISTEN_ADDRESS=192.168.1.202
    ports:
      - "9042:9042"
    depends_on:
      cassandra-host-2:
        condition: service_healthy

networks:
  cassandra-local:
    driver: macvlan
    driver_opts:
      parent: enp0s3
    ipam:
      config:
        - subnet: 192.168.1.0/24
          gateway: 192.168.1.1
          ip_range: 192.168.1.200/30